server:
  port: ${SPRING_SIMPLE_REST_API_PORT:8451}

spring:
  application:
    name: SimpleRestApi
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password

logging:
  file:
    name: ${SPRING_SIMPLE_REST_LOG_FILE_NAME:logs/simple_rest_api.log}
  rolling-policy:
    file-name-pattern: ${SPRING_SIMPLE_REST_LOG_FILE_NAME_PATTERN:logs/myapp.%d{yyyy-MM-dd}.%i.log}
    clean-history-on-start: false
    max-history: 5
    total-size-cap: 20MB
  appender:
    file:
      prudent: true